name : "Deploy the Pipeline"
on:  workflow_dispatch
jobs:
    deploy:
        runs-on: self-hosted
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4 
            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.14'
            - name: Verify the Version
              run : python --version
            - name: Intalling Request
              run: pip install requests
            - name: intalling dotenv
              run: python -m pip install python-dotenv
            - name: Run The File
              run : python index.py 
            - name: Final check for the EC2
              run: echo "Mail Sended Succefully">>LogFile1.txt